searcher/catalog/urls.py
from django.urls import path

from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.products, name='products'),
    path('products/<int:id>/', views.products_detail, name='products_detail'),
    path('providers/', views.providers, name='providers'),
    path('providers/<int:id>/', views.providers_detail,
         name='providers_detail'),
]

searcher/searcher/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog'))
]

searcher/catalog/models.py
from django.db import models


class Provider(models.Model):
    name = models.CharField(
        max_length=256,
        verbose_name='Имя поставщика'
    )
    number = models.CharField(
        max_length=20,
        verbose_name='Номер телефона',
        blank=True
    )
    email = models.CharField(
        max_length=50,
        verbose_name='Email',
        blank=True
    )
    url = models.URLField(
        verbose_name='Сайт поставщика',
        blank=True
    )
    brand = models.CharField(
        max_length=25,
        verbose_name='Бренд'
    )

    class Meta:
        verbose_name = "Поставщик"
        verbose_name_plural = "Поставщики"

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(
        max_length=256,
        verbose_name='Наименование'
    )
    search_field = models.CharField(
        max_length=256,
        verbose_name='Поисковая строка'
    )
    provider = models.ForeignKey(
        Provider,
        on_delete=models.CASCADE,
        verbose_name='Поставщик'
    )
    price_for_unit = models.FloatField(
        verbose_name='Цена за еденицу товара'
    )
    unit_type = models.CharField(
        max_length=20,
        verbose_name='Единица измерения'
    )
    in_box = models.CharField(
        max_length=20,
        verbose_name='Единица измерения в коробке',
        blank=True
    )
    country = models.CharField(
        max_length=100,
        verbose_name='Страна-изготовитель',
        blank=True
    )
    code = models.CharField(
        max_length=40,
        verbose_name='Код товара',
        blank=True
    )

    class Meta:
        verbose_name = ("Продукт")
        verbose_name_plural = ("Продукты")

    def __str__(self):
        return self.title

searcher/catalog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Provider


def products(request):
    search_query = request.GET.get('search', '')

    if search_query:
        if len(search_query) > 4:
            search_query = search_query[1:-1]
        product_list = (Product
                        .objects
                        .select_related('provider')
                        .filter(search_field__icontains=search_query)
                        .order_by('-price_for_unit'))
    else:
        product_list = (Product
                        .objects
                        .select_related('provider')
                        .order_by('-price_for_unit')
                        .all())
    context = {
        'product_list': product_list,
    }
    return render(request, 'catalog/products.html', context)


def products_detail(request, id):
    product = get_object_or_404(Product, id=id)
    context = {
        'product': product
    }
    return render(request, 'catalog/products_detail.html', context)


def providers(request):
    provider_list = Provider.objects.all()
    context = {
        'provider_list': provider_list
    }
    return render(request, 'catalog/providers.html', context)


def providers_detail(request, id):
    provider = get_object_or_404(Provider, id=id)
    product_list = Product.objects.filter(provider=provider)
    context = {
        'provider': provider,
        'product_list': product_list,
    }
    return render(request, 'catalog/providers_detail.html', context)

searcher/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/logo.ico' %}" type="image">
    <title>
      {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  </head>
  <body>
    {% include "includes/header.html" %}
    <main>
      <div class="container py-5">
      {% block content %}{% endblock %}
      </div>
    </main>
    {% include "includes/footer.html" %}   
  </body>
</html>

searcher/templates/catalog/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Продукты
{% endblock %}

{% block content %}
  <form class="mb-3" action="{% url 'catalog:products' %}">
    <div class="mb-3">
      <input class="form-control" type="search" placeholder="Поиск" aria-label="Поиск" name="search">
    </div>
    <button class="btn btn-primary" type="submit">Искать</button>
  </form>


  {% for product in product_list %}
    <article>
      {% include "includes/product_card.html" %}
    </article>
  {% endfor %}
{% endblock %}

searcher/templates/catalog/products_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
{{ product.title }}
{% endblock %}

{% block content%}
  <article>
    <h5>{{ product.title }}</h5>
    <p>{{ product.price_for_unit }} за {{ product.unit_type }}</p>
    <p></p>
    <p></p>
  </article> 

{% endblock%}

searcher/templates/catalog/providers.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Поставщики
{% endblock %}

{% block content %}
  <h1 class="mb-5"></h1>
  {% for provider in provider_list %}
    <article class-"mb-5">
        <div class="card">
            <div class="card-body">
              <h5 class="card-title"><a href="{% url 'catalog:providers_detail' provider.id %}">{{ provider.name }}</a></h5>
            </div>
          </div>          
    </article>
  {% endfor %}
{% endblock %}

searcher/templates/catalog/providers_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{ provider.brand }}
{% endblock %}

{% block content %}
  <article>
    <h3>{{ provider.name }}</h3>
    <p>Сокращенное название: {{ provider.brand }}</p>
    {% if provider.email %}<p>Электронная почта: {{ provider.email }}</p>{% endif %}
    {% if provider.number %}<p>Номер телефона: {{ provider.number }}</p>{% endif %}
    {% if provider.url %}<p>Url: <a href="{{provider.url}}">{{ provider.url }}</a></p>{% endif %}
  </article> 
  <h1>Все продукты поставщика</h1>
  {% for product in product_list %}
    <article class-"mb-5">
      {% include "includes/product_card.html" %}
    </article>
  {% endfor %}

{% endblock %}

searcher/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <p>© запилил как смог</p>    
  </footer>

searcher/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      {% with request.resolver_match.view_name as view_name %}        
        <ul class="nav  nav-pills">
          <li class="nav-item">              
            <a class="nav-link {% if view_name == 'catalog:products' %} active {% endif %}" href="{% url 'catalog:products' %}">
              Каталог продуктов
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'catalog:providers' %} active {% endif %}" href="{% url 'catalog:providers' %}">
              Поставщики
            </a>
          </li>
        </ul>
      {% endwith %}      
    </div>
  </nav> 
</header>

searcher/templates/includes/product_card.html
<h5 class="card-title">{{ product.title }}<a href="{% url 'catalog:products_detail' product.id %}"></a></h5>
<h6 class="card-subtitle mb-2 text-muted">
      {{ product.price_for_unit }}₽ за {{ product.unit_type }}; {% if product.in_box %}в коробке: {{ product.in_box }}{% endif %} <a href="{% url 'catalog:providers_detail' product.provider.id %}">{{ product.provider.brand }}</a>
</h6>
</hr>